### PR TITLE
Add Rust translation

### PR DESCRIPTION
**Pull request by sreyhani**
Hi,
I've made the Rust version of this kata. we're going to use it at a dojo session in our workplace.
It uses Insta crate for approval test.

### CODE REVIEW

**Comment by codecop** [comment]
Thank you. Are there no records or structs in Rust? The usage of Json and '.as_array().unwrap()' looks odd. All other languages use dedicated object types or classes for Performance, Play and Invoice.

**Comment by emilybache** [comment]
Actually Peter the original is javascript and it just loads the json directly into generic datastructures not named object classes. I think those classes first appeared in the Java or C version where it was just too hard to load json otherwise. Anyway - the idea would be to do something that works in Rust - would it be normal to load json into generic datastructures containing primitives?

**Comment by sreyhani** [comment]
There are structs in Rust, but I think it's better to keep it like the original javascript and cpp version and leave defining those structs as a part of the refactoring process to decouple dealing with json logic from business logic.

the [serde](https://github.com/serde-rs/json) library offers both loading json into strongly typed structs and loading it into untyped generic `Value` datastructure. when you know exactly how your data is structured it's better to use the former one, as it removes the need for those ugly typecasts and `unwraps` and checks everything compile time.

**Comment by emilybache** [comment]
Thanks, let's go with this.

**Pull request merged**
